#Setup
title: "Genomic Insights into MEF2C"
description: "An independent bioinformatics exploration of Myocyte enhancer factor 2C."
baseurl: https://aaa-pyqueen.github.io/MEF2C-Data/
url: https://aaa-pyqueen.github.io/MEF2C-Data/home.html/
author: "Aquesha A. Addison, RHIA"

Collections:
  _pages:
    output: true
  projects:
    output: true
  references:
    output:  true

#Dependencies
markdown: kramdown
highlighter: rouge
theme: minima
