#Setup
title: "Genomic Insights into MEF2C"
description: "An independent bioinformatics exploration of Myocyte enhancer factor 2C."
author: "Aquesha A. Addison, RHIA"

#Repository
baseurl: /MEF2C-Data/
url: https://aaa-pyqueen.github.io
branch: main
permalink: pretty


collections:
  layouts:
    output: false
  pages:
    output: true
  projects:
    output: true
  references:
    output:  true
##################################################################
#Dependencies & Customizations
markdown: kramdown
highlighter: rouge
theme: minima

minima:
  skin: solarized-dark-mode

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-github-metadata
  - nokogiri
  - safe-yaml
###################################################################
#HTML-specific settings
html:
  home_page_in_navbar: false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://aaa-pyqueen.github.io/MEF2C-Data/

#######################################################
#Enable React App Embedding
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - yarn.lock
  - webpack.config.js

include:
  - pages
