#Setup
title: "Genomic Insights into MEF2C"
description: "An independent bioinformatics exploration of Myocyte enhancer factor 2C."
baseurl: ""
url: https://aaa-pyqueen.github.io/MEF2C-Data/home.html/
author: "Aquesha A. Addison, RHIA"

Collections:
  _pages:
    output: true
  projects:
    output: true
  references:
    output:  true

#Dependencies
markdown:         kramdown
highlighter:      rouge
theme: jekyll-theme-minimal

plugins:
  
include:
  - _pages
  - _layouts
  - static
  - templates
  - assets

  nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Projects"
    url: "/projects/"
  - title: "References"
    url: "/references/"
  - title: "Gallery"
    url: "/gallery/"
  - title: "Data"
    url: "/data/"
